
(define (problem line-3)
  (:domain tireworld)
  (:objects l1 l2 l3 l4 l5 l6 l7 - location)
  (:init (vehicle-at l1)
    (road l1 l2)
    (road l2 l3)
    (road l3 l4)
    (road l4 l5)
    (road l5 l6)
    (road l6 l7)
    (spare-in l1)
    (spare-in l2)
    (spare-in l3)
    (spare-in l4)
    (spare-in l5)
    (spare-in l6)
    (spare-in l7)
    (not-flattire)
)
  (:goal (vehicle-at l7)))

